/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ConnectionStatus: typeof import('./src/components/Navbar/ConnectionStatus.vue')['default']
    CurrentSpeed: typeof import('./src/components/Navbar/CurrentSpeed.vue')['default']
    FreeSpace: typeof import('./src/components/Navbar/FreeSpace.vue')['default']
    Navbar: typeof import('./src/components/Navbar/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpeedCard: typeof import('./src/components/Core/SpeedCard.vue')['default']
    SpeedGraph: typeof import('./src/components/Navbar/SpeedGraph.vue')['default']
    StorageCard: typeof import('./src/components/Core/StorageCard.vue')['default']
    TransferStats: typeof import('./src/components/Navbar/TransferStats.vue')['default']
  }
}
