blank_issues_enabled: true
contact_links:
  - name: Discord
    url: https://discord.gg/KDQP7fR467
    about: Join the discord server to contact us directly
  - name: Email
    url: mailto:vuetorrent@larsluph.dev
    about: Or sent us a mail for private requests
