export enum DashboardProperty {
  SIZE = 'Size',
  PROGRESS = 'Progress',
  DOWNLOAD = 'Download',
  UPLOAD = 'Upload',
  DOWNLOADED = 'Downloaded',
  DIRECTORY = 'Directory',
  UPLOADED = 'Uploaded',
  ETA = 'ETA',
  PEERS = 'Peers',
  SEEDS = 'Seeds',
  STATUS = 'Status',
  RATIO = 'Ratio',
  TRACKER = 'Tracker',
  CATEGORY = 'Category',
  TAGS = 'Tags',
  ADDED_ON = 'AddedOn',
  AVAILABILITY = 'Availability',
  LAST_ACTIVITY = 'LastActivity',
  COMPLETED_ON = 'CompletedOn',
  GLOBAL_SPEED = 'GlobalSpeed',
  GLOBAL_VOLUME = 'GlobalVolume'
}
